name: Android

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-number:
    uses: ./.github/workflows/build-number.yml

  build-debug:
    needs: build-number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
          cache-write-only: ${{ github.event_name == 'push' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew composeApp:assembleDebug -Pbuild-number=${{ needs.build-number.outputs.build-number }}

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: Android Debug Archive
          path: ${{ github.workspace }}/**/build/**/*.apk

  build-release:
    needs: build-number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          # Only write to the cache for builds on the 'main' and 'release' branches. (Default is 'main' only.)
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
          cache-write-only: ${{ github.event_name == 'push' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew composeApp:assembleRelease -Pbuild-number=${{ needs.build-number.outputs.build-number }}

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: Android Release Archive
          path: ${{ github.workspace }}/**/build/**/*.apk